# Generated by Django 5.1.4 on 2024-12-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='companies/'),
        ),
    ]
