# Generated by Django 5.1.4 on 2024-12-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_education_gpa_education_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Özel ikon resmi', null=True, upload_to='skills/'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, help_text='Font Awesome ikon kodu (örn: fab fa-python)', max_length=50, null=True),
        ),
    ]
